# Generated by Django 4.2.7 on 2026-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_aadhaar_image_user_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qrs/'),
        ),
    ]
